import { eq } from 'drizzle-orm'
import { db } from '@/lib/db'
import { mockServerConfigs, mockRequestLogs } from '@/lib/schema-mock'
import { openapiSources } from '@/lib/schema-openapi'
import { parseOpenAPISpec } from '@/lib/openapi/parser'
import { generateMockResponse } from './generator'

interface MockResult {
  status: number
  body: unknown
  headers: Record<string, string>
}

export async function handleMockRequest(
  configId: string,
  method: string,
  path: string,
): Promise<MockResult> {
  const start = Date.now()

  const config = await db.query.mockServerConfigs.findFirst({
    where: eq(mockServerConfigs.id, configId),
  })

  if (!config) {
    return { status: 404, body: { error: 'Mock server not found' }, headers: {} }
  }

  if (!config.enabled) {
    return { status: 503, body: { error: 'Mock server is disabled' }, headers: {} }
  }

  const source = await db.query.openapiSources.findFirst({
    where: eq(openapiSources.id, config.openapiSourceId),
  })

  if (!source) {
    return { status: 404, body: { error: 'OpenAPI source not found' }, headers: {} }
  }

  // Check overrides
  const overrides = (config.overrides ?? {}) as Record<string, unknown>
  const overrideKey = `${method.toUpperCase()} ${path}`
  if (overrides[overrideKey] !== undefined) {
    await logRequest(config.id, method, path, 200, Date.now() - start)
    if (config.delay > 0) await delay(config.delay)
    return { status: 200, body: overrides[overrideKey], headers: { 'x-mock-override': 'true' } }
  }

  // Apply error rate
  if (config.errorRate > 0 && Math.random() < config.errorRate) {
    const duration = Date.now() - start
    await logRequest(config.id, method, path, 500, duration)
    if (config.delay > 0) await delay(config.delay)
    return {
      status: 500,
      body: { error: 'Simulated server error', message: 'This error was generated by the mock server error rate setting.' },
      headers: { 'x-mock-error': 'simulated' },
    }
  }

  // Parse spec and find matching endpoint
  let spec
  try {
    spec = await parseOpenAPISpec(source.rawContent)
  } catch {
    return { status: 500, body: { error: 'Failed to parse OpenAPI spec' }, headers: {} }
  }

  const endpoint = findMatchingEndpoint(spec.endpoints, method, path)
  if (!endpoint) {
    await logRequest(config.id, method, path, 404, Date.now() - start)
    return {
      status: 404,
      body: { error: 'Endpoint not found', method, path, message: 'No matching endpoint in OpenAPI spec.' },
      headers: {},
    }
  }

  // Find success response schema
  const { statusCode, schema } = findSuccessResponse(endpoint.responses, spec.rawSchemas)

  if (config.delay > 0) await delay(config.delay)

  const body = schema ? generateMockResponse(schema, config.seed ?? undefined) : null
  const duration = Date.now() - start

  await logRequest(config.id, method, path, statusCode, duration)

  return {
    status: statusCode,
    body,
    headers: {
      'x-mock-matched-operation': endpoint.operationId ?? `${endpoint.method} ${endpoint.path}`,
      'x-mock-response-time': `${duration}ms`,
    },
  }
}

function findMatchingEndpoint(
  endpoints: { path: string; method: string; operationId?: string; responses: Record<string, unknown> }[],
  method: string,
  requestPath: string,
) {
  const upperMethod = method.toUpperCase()

  // Exact match first
  const exact = endpoints.find(
    (e) => e.method === upperMethod && e.path === requestPath,
  )
  if (exact) return exact

  // Parameterized path matching
  for (const ep of endpoints) {
    if (ep.method !== upperMethod) continue
    if (matchParameterizedPath(ep.path, requestPath)) return ep
  }

  return null
}

function matchParameterizedPath(template: string, actual: string): boolean {
  const templateParts = template.split('/').filter(Boolean)
  const actualParts = actual.split('/').filter(Boolean)

  if (templateParts.length !== actualParts.length) return false

  return templateParts.every((part, i) =>
    part.startsWith('{') && part.endsWith('}')
      ? true
      : part === actualParts[i],
  )
}

function findSuccessResponse(
  responses: Record<string, unknown>,
  rawSchemas: Record<string, unknown>,
): { statusCode: number; schema: Record<string, unknown> | null } {
  for (const code of ['200', '201', '202', '203']) {
    const resp = responses[code] as Record<string, unknown> | undefined
    if (resp) {
      const schema = extractSchema(resp, rawSchemas)
      return { statusCode: parseInt(code), schema }
    }
  }

  if (responses['204']) {
    return { statusCode: 204, schema: null }
  }

  // Default response
  const def = responses['default'] as Record<string, unknown> | undefined
  if (def) {
    return { statusCode: 200, schema: extractSchema(def, rawSchemas) }
  }

  return { statusCode: 200, schema: null }
}

function extractSchema(
  response: Record<string, unknown>,
  rawSchemas: Record<string, unknown>,
): Record<string, unknown> | null {
  const content = response.content as Record<string, unknown> | undefined
  if (!content) return (response.schema as Record<string, unknown>) ?? null

  const json = content['application/json'] as Record<string, unknown> | undefined
  if (!json) {
    const first = Object.values(content)[0] as Record<string, unknown> | undefined
    if (first?.schema) return resolveRefs(first.schema, rawSchemas) as Record<string, unknown>
    return null
  }

  if (json.schema) return resolveRefs(json.schema, rawSchemas) as Record<string, unknown>
  return null
}

function resolveRefs(schema: unknown, rawSchemas: Record<string, unknown>, depth = 0): unknown {
  if (!schema || typeof schema !== 'object' || depth > 10) return schema

  const s = schema as Record<string, unknown>

  if (s.$ref && typeof s.$ref === 'string') {
    const refPath = s.$ref.replace('#/components/schemas/', '')
    const resolved = rawSchemas[refPath]
    if (resolved) return resolveRefs(resolved, rawSchemas, depth + 1)
    return schema
  }

  if (s.properties && typeof s.properties === 'object') {
    const resolved: Record<string, unknown> = { ...s, properties: {} }
    const props = resolved.properties as Record<string, unknown>
    for (const [key, value] of Object.entries(s.properties as Record<string, unknown>)) {
      props[key] = resolveRefs(value, rawSchemas, depth + 1)
    }
    return resolved
  }

  if (s.items) {
    return { ...s, items: resolveRefs(s.items, rawSchemas, depth + 1) }
  }

  if (s.allOf) {
    return { ...s, allOf: (s.allOf as unknown[]).map((sub) => resolveRefs(sub, rawSchemas, depth + 1)) }
  }

  if (s.oneOf) {
    return { ...s, oneOf: (s.oneOf as unknown[]).map((sub) => resolveRefs(sub, rawSchemas, depth + 1)) }
  }

  if (s.anyOf) {
    return { ...s, anyOf: (s.anyOf as unknown[]).map((sub) => resolveRefs(sub, rawSchemas, depth + 1)) }
  }

  return schema
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

async function logRequest(
  configId: string,
  method: string,
  path: string,
  statusCode: number,
  duration: number,
) {
  try {
    await db.insert(mockRequestLogs).values({
      configId,
      method: method.toUpperCase(),
      path,
      statusCode,
      duration,
    })
  } catch {
    // Non-blocking: don't fail the mock response if logging fails
  }
}
